# Generated by Django 4.0.3 on 2022-03-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
